framework:
    rate_limiter:
        login_attempts:
            policy: 'sliding_window'
            limit: 5
            interval: '15 minutes'
        registration_attempts:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
        resend_verification_attempts:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
        forgot_password_attempts:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
        message_attempts:
            policy: 'sliding_window'
            limit: 20
            interval: '5 minutes'
        rendez_vous_attempts:
            policy: 'sliding_window'
            limit: 5
            interval: '1 hour'
        contact_attempts:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
        contact_reply_attempts:
            policy: 'sliding_window'
            limit: 30
            interval: '15 minutes'

