
security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
    role_hierarchy:
        ROLE_MODERATEUR: ROLE_CLIENT
        ROLE_ADMIN: ROLE_MODERATEUR

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|uploads)/
            security: false

        login:
            pattern: ^/api/login_check$
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            jwt: ~

when@dev:
    security:
        access_control:
            - { path: ^/api/login, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/, roles: PUBLIC_ACCESS }
            - { path: ^/api/annonces/publiques, methods: [GET], roles: PUBLIC_ACCESS }
            - { path: ^/api/utilisateurs$, methods: [POST], roles: PUBLIC_ACCESS }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        access_control:
            - { path: ^/api/login, roles: PUBLIC_ACCESS }
            - { path: ^/api/auth/, roles: PUBLIC_ACCESS }
            - { path: ^/api/annonces/publiques, methods: [GET], roles: PUBLIC_ACCESS }
            - { path: ^/api/utilisateurs$, methods: [POST], roles: PUBLIC_ACCESS }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@prod:
    security:
        access_control:
            - { path: ^/api/login, roles: PUBLIC_ACCESS, requires_channel: https }
            - { path: ^/api/auth/, roles: PUBLIC_ACCESS, requires_channel: https }
            - { path: ^/api/annonces/publiques, methods: [GET], roles: PUBLIC_ACCESS, requires_channel: https }
            - { path: ^/api/utilisateurs$, methods: [POST], roles: PUBLIC_ACCESS, requires_channel: https }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }