<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922101108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE annonce (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, prix NUMERIC(10, 2) NOT NULL, statut VARCHAR(20) NOT NULL, date_publication TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vehicule_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F65593E54A4A3511 ON annonce (vehicule_id)');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(20) NOT NULL, client_id INT NOT NULL, moderateur_id INT DEFAULT NULL, annonce_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A8E26E919EB6921 ON conversation (client_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E920A01F78 ON conversation (moderateur_id)');
        $this->addSql('CREATE INDEX IDX_8A8E26E98805AB2F ON conversation (annonce_id)');
        $this->addSql('CREATE TABLE facture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_facture VARCHAR(50) NOT NULL, date_emission DATE NOT NULL, montant_total NUMERIC(10, 2) NOT NULL, statut VARCHAR(20) NOT NULL, intervention_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE8664108EAE3863 ON facture (intervention_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FACTURE_NUMERO ON facture (numero_facture)');
        $this->addSql('CREATE TABLE intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_intervention DATE NOT NULL, description TEXT DEFAULT NULL, kilometrage_releve INT DEFAULT NULL, cout_total NUMERIC(10, 2) NOT NULL, statut VARCHAR(20) NOT NULL, vehicule_id INT NOT NULL, rendez_vous_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D11814AB91EF7EAA ON intervention (rendez_vous_id)');
        $this->addSql('CREATE INDEX IDX_D11814AB4A4A3511 ON intervention (vehicule_id)');
        $this->addSql('CREATE TABLE intervention_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_applique NUMERIC(10, 2) NOT NULL, intervention_id INT NOT NULL, service_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA73EEB78EAE3863 ON intervention_service (intervention_id)');
        $this->addSql('CREATE INDEX IDX_AA73EEB7ED5CA9E6 ON intervention_service (service_id)');
        $this->addSql('CREATE TABLE ligne_facture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(10, 2) NOT NULL, sous_total NUMERIC(10, 2) NOT NULL, facture_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_611F5A297F2DEE08 ON ligne_facture (facture_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lu BOOLEAN DEFAULT false NOT NULL, conversation_id INT NOT NULL, expediteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F10335F61 ON message (expediteur_id)');
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(500) NOT NULL, ordre_affichage INT DEFAULT NULL, annonce_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B784188805AB2F ON photo (annonce_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, motif VARCHAR(255) DEFAULT NULL, statut VARCHAR(20) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, vehicule_id INT NOT NULL, moderateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A19EB6921 ON rendez_vous (client_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A4A4A3511 ON rendez_vous (vehicule_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A20A01F78 ON rendez_vous (moderateur_id)');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, prix_standard NUMERIC(10, 2) NOT NULL, duree_estimee INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_UTILISATEUR_EMAIL ON utilisateur (email)');
        $this->addSql('CREATE TABLE vehicule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marque VARCHAR(100) NOT NULL, modele VARCHAR(100) NOT NULL, annee INT NOT NULL, immatriculation VARCHAR(20) NOT NULL, vin VARCHAR(50) DEFAULT NULL, kilometrage INT NOT NULL, couleur VARCHAR(50) DEFAULT NULL, date_ajout TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, proprietaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_VEHICULE_IMMATRICULATION ON vehicule (immatriculation)');
        $this->addSql('CREATE INDEX IDX_292FFF1D76C50E4A ON vehicule (proprietaire_id)');
        $this->addSql('ALTER TABLE annonce ADD CONSTRAINT FK_F65593E54A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E919EB6921 FOREIGN KEY (client_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E920A01F78 FOREIGN KEY (moderateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E98805AB2F FOREIGN KEY (annonce_id) REFERENCES annonce (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE8664108EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB91EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id)');
        $this->addSql('ALTER TABLE intervention_service ADD CONSTRAINT FK_AA73EEB78EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention_service ADD CONSTRAINT FK_AA73EEB7ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_facture ADD CONSTRAINT FK_611F5A297F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784188805AB2F FOREIGN KEY (annonce_id) REFERENCES annonce (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A19EB6921 FOREIGN KEY (client_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A20A01F78 FOREIGN KEY (moderateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE vehicule ADD CONSTRAINT FK_292FFF1D76C50E4A FOREIGN KEY (proprietaire_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annonce DROP CONSTRAINT FK_F65593E54A4A3511');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E919EB6921');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E920A01F78');
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_8A8E26E98805AB2F');
        $this->addSql('ALTER TABLE facture DROP CONSTRAINT FK_FE8664108EAE3863');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB4A4A3511');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB91EF7EAA');
        $this->addSql('ALTER TABLE intervention_service DROP CONSTRAINT FK_AA73EEB78EAE3863');
        $this->addSql('ALTER TABLE intervention_service DROP CONSTRAINT FK_AA73EEB7ED5CA9E6');
        $this->addSql('ALTER TABLE ligne_facture DROP CONSTRAINT FK_611F5A297F2DEE08');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F10335F61');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B784188805AB2F');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A19EB6921');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A4A4A3511');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A20A01F78');
        $this->addSql('ALTER TABLE vehicule DROP CONSTRAINT FK_292FFF1D76C50E4A');
        $this->addSql('DROP TABLE annonce');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE intervention_service');
        $this->addSql('DROP TABLE ligne_facture');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE vehicule');
    }
}
