<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928173500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create password_reset_token table and add password_changed_at to utilisateur';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_ip VARCHAR(45) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_RESET_TOKEN_HASH ON password_reset_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_RESET_TOKEN_USER ON password_reset_token (user_id)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_RESET_TOKEN_USER FOREIGN KEY (user_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD password_changed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_reset_token DROP CONSTRAINT FK_RESET_TOKEN_USER');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('ALTER TABLE utilisateur DROP password_changed_at');
    }
}
