<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001191805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, telephone VARCHAR(30) DEFAULT NULL, sujet VARCHAR(150) DEFAULT NULL, message TEXT NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(20) NOT NULL, reponse TEXT DEFAULT NULL, date_reponse TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ip_adresse VARCHAR(45) DEFAULT NULL, repond_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_message_contact_statut ON message_contact (statut)');
        $this->addSql('CREATE INDEX idx_message_contact_date_envoi ON message_contact (date_envoi)');
        $this->addSql('CREATE INDEX IDX_DCEADC345938D37B ON message_contact (repond_par_id)');
        $this->addSql('ALTER TABLE message_contact ADD CONSTRAINT FK_DCEADC345938D37B FOREIGN KEY (repond_par_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_contact DROP CONSTRAINT FK_DCEADC345938D37B');
        $this->addSql('DROP TABLE message_contact');
    }
}
